const $ = (selector) => document.querySelector(selector);
const cash = new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 });
function toast(message, isError = false) { const element = $('#toast'); element.textContent = message; element.classList.toggle('error', isError); element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 3400); }
async function request(url, options) { const response = await fetch(url, { headers: { 'content-type': 'application/json' }, ...options }); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; }
function updateDestinations(state) { const origin = state.aircraft[0].location; const selected = $('#destination').value; $('#origin').textContent = origin; $('#destination').innerHTML = state.airports.filter((airport) => airport.code !== origin).map((airport) => `<option value="${airport.code}">${airport.name} · ${airport.code}</option>`).join(''); if ([...$('#destination').options].some((option) => option.value === selected)) $('#destination').value = selected; }
function render(state) { const plane = state.aircraft[0]; const flights = state.flights; const active = flights.filter((flight) => flight.status !== 'COMPLETADO'); $('#cash').textContent = cash.format(state.airline.cash); $('#aircraft-status').textContent = plane.available ? 'Disponible' : 'Asignado'; $('#aircraft-detail').textContent = `${plane.registration} · ${plane.model} · ${plane.condition}% condición · ${plane.location}`; $('#active-flights').textContent = active.length; const completed = flights.find((flight) => flight.status === 'COMPLETADO'); $('#last-result').textContent = completed ? cash.format(completed.revenue) : '—'; $('#ledger-note').textContent = state.ledger[0]?.note || 'Sin movimientos'; $('#maintain').disabled = !plane.available; $('#flight-list').innerHTML = flights.length ? flights.map((flight) => `<article class="flight"><div><span class="status ${flight.status.toLowerCase().replace(' ', '-')}">${flight.status}</span><strong>${flight.code}</strong><p>${flight.origin} <b>→</b> ${flight.destination} · ${flight.aircraft}</p></div><div class="flight-values"><b>${flight.passengers} pasajeros</b><span>${cash.format(flight.revenue)} resultado</span>${flight.status === 'EN VUELO' ? `<div class="progress"><i style="width:${flight.progress}%"></i></div>` : ''}</div></article>`).join('') : '<p class="empty">Aún no hay vuelos programados. Crea tu primera ruta para poner el mundo en marcha.</p>'; $('#ledger-list').innerHTML = state.ledger.map((entry) => `<div><span>${entry.note}</span><b class="${entry.amount >= 0 ? 'positive' : 'negative'}">${entry.amount >= 0 ? '+' : ''}${cash.format(entry.amount)}</b></div>`).join(''); updateDestinations(state); }
async function refresh() { try { render(await request('/api/state')); await quote(); } catch (error) { toast(error.message, true); } }
async function quote() { const destination = $('#destination').value; if (!destination) return; try { const data = await request('/api/routes/analyse', { method: 'POST', body: JSON.stringify({ origin: $('#origin').textContent, destination }) }); $('#price').value = data.fare; $('#quote').innerHTML = `<div><b>${data.origin.code} → ${data.airport.code}</b><span>${data.distance.toLocaleString('es-ES')} km · ${data.expectedPassengers} pasajeros estimados</span></div><div><b class="positive">${cash.format(data.expectedProfit)}</b><span>beneficio estimado</span></div>`; } catch (error) { toast(error.message, true); } }
$('#destination').addEventListener('change', quote);
$('#schedule').addEventListener('click', async () => { const button = $('#schedule'); button.disabled = true; try { const data = await request('/api/flights', { method: 'POST', body: JSON.stringify({ destination: $('#destination').value, price: $('#price').value }) }); toast(`${data.flight.code} programado: ${data.flight.origin} → ${data.flight.destination}.`); await refresh(); } catch (error) { toast(error.message, true); } finally { button.disabled = false; } });
$('#maintain').addEventListener('click', async () => { try { const data = await request('/api/maintenance', { method: 'POST', body: '{}' }); toast(`Mantenimiento programado por ${cash.format(data.cost)}.`); await refresh(); } catch (error) { toast(error.message, true); } });
$('#reset').addEventListener('click', async () => { if (!confirm('¿Restablecer la aerolínea y eliminar los vuelos de prueba?')) return; await request('/api/reset', { method: 'POST' }); toast('Mundo restablecido.'); refresh(); });
refresh(); setInterval(refresh, 2500);
