const { readFile, writeFile, mkdir } = require('node:fs/promises');
const path = require('node:path');
const FLIGHT_DURATION_MS = 90_000;
const TURNAROUND_MS = 20_000;
const airports = {
  PMI: { code: 'PMI', name: 'Palma de Mallorca', demand: 1.12, latitude: 39.55, longitude: 2.74 },
  LGW: { code: 'LGW', name: 'Londres Gatwick', demand: 1.24, latitude: 51.15, longitude: -0.18 },
  DUS: { code: 'DUS', name: 'Düsseldorf', demand: 1.18, latitude: 51.29, longitude: 6.77 },
  FCO: { code: 'FCO', name: 'Roma Fiumicino', demand: 1.04, latitude: 41.8, longitude: 12.24 },
  AMS: { code: 'AMS', name: 'Ámsterdam Schiphol', demand: 1.14, latitude: 52.31, longitude: 4.76 }
};
const template = () => ({
  airline: { id: 'airline-atlas', name: 'Atlas Air', code: 'AAA', hub: 'PMI', cash: 50_000_000, reputation: 92 },
  aircraft: [{ id: 'ec-nmr', registration: 'EC-NMR', model: 'Airbus A320neo', seats: 180, location: 'PMI', condition: 88, hours: 1240, cycles: 881, availableAt: 0, maintenanceUntil: 0 }],
  flights: [],
  ledger: [{ id: 'initial-capital', at: new Date().toISOString(), type: 'capital', amount: 50_000_000, note: 'Capital inicial de la aerolínea' }]
});
function error(message, statusCode = 400) { const result = new Error(message); result.statusCode = statusCode; return result; }
function radians(value) { return value * Math.PI / 180; }
function distanceBetween(origin, destination) { const a = airports[origin]; const b = airports[destination]; if (!a || !b || origin === destination) throw error('La combinación de aeropuertos no está disponible.'); const lat = radians(b.latitude - a.latitude); const lon = radians(b.longitude - a.longitude); const h = Math.sin(lat / 2) ** 2 + Math.cos(radians(a.latitude)) * Math.cos(radians(b.latitude)) * Math.sin(lon / 2) ** 2; return Math.round(6371 * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h))); }
function flightStatus(flight, now) { const elapsed = now - flight.departureAt; if (elapsed < 0) return 'PROGRAMADO'; if (elapsed < 12_000) return 'EMBARQUE'; if (elapsed < FLIGHT_DURATION_MS) return 'EN VUELO'; if (elapsed < FLIGHT_DURATION_MS + TURNAROUND_MS) return 'ROTACIÓN'; return 'COMPLETADO'; }
function publicFlight(flight, now) { return { ...flight, status: flightStatus(flight, now), progress: Math.max(0, Math.min(100, Math.round(((now - flight.departureAt) / FLIGHT_DURATION_MS) * 100))) }; }
function calculate(origin, destination, seats) { const airport = airports[destination]; const distance = distanceBetween(origin, destination); const fare = Math.round(76 + distance * 0.071); const expectedPassengers = Math.min(seats, Math.round(seats * (0.59 + airport.demand * 0.24))); const fuel = Math.round(distance * 2.4); const airportFees = Math.round(2_600 + distance * 1.1); const operatingCost = fuel + airportFees + 5_850; return { origin: airports[origin], airport, distance, fare, expectedPassengers, fuel, airportFees, operatingCost, expectedRevenue: fare * expectedPassengers, expectedProfit: fare * expectedPassengers - operatingCost }; }
function createStore(file) {
  let queue = Promise.resolve();
  async function transact(work) { queue = queue.then(work, work); return queue; }
  async function load() { try { return JSON.parse(await readFile(file, 'utf8')); } catch (err) { if (err.code !== 'ENOENT') throw err; const state = template(); await save(state); return state; } }
  async function save(state) { await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, JSON.stringify(state, null, 2)); }
  function settle(state, now) { let changed = false; for (const flight of state.flights) { if (!flight.settled && flightStatus(flight, now) === 'COMPLETADO') { flight.settled = true; state.airline.cash += flight.revenue; const aircraft = state.aircraft.find(item => item.id === flight.aircraftId); aircraft.location = flight.destination; aircraft.condition = Math.max(1, aircraft.condition - 1); aircraft.hours += flight.durationHours; aircraft.cycles += 1; state.ledger.unshift({ id: `flight-${flight.id}`, at: new Date(now).toISOString(), type: 'flight-settlement', amount: flight.revenue, note: `${flight.code} · ${flight.origin} → ${flight.destination}` }); changed = true; } } return changed; }
  async function withState(work) { return transact(async () => { const state = await load(); const changed = settle(state, Date.now()); const output = await work(state); if (changed || output?.save) await save(state); return output?.value ?? output; }); }
  return {
    state: () => withState(async (state) => { const now = Date.now(); return { value: { airline: state.airline, aircraft: state.aircraft.map(({ availableAt, maintenanceUntil = 0, ...plane }) => ({ ...plane, available: availableAt <= now && maintenanceUntil <= now, maintenanceRequired: plane.condition < 65 })), flights: state.flights.map(flight => publicFlight(flight, now)).sort((a, b) => b.departureAt - a.departureAt), ledger: state.ledger.slice(0, 6), airports: Object.values(airports) } }; }),
    advance: () => withState(async () => ({ value: null, save: true })),
    analyse: ({ origin = 'PMI', destination, aircraftId = 'ec-nmr' }) => withState(async (state) => { const aircraft = state.aircraft.find(item => item.id === aircraftId); if (!aircraft) throw error('Avión no encontrado.', 404); return { value: calculate(origin, destination, aircraft.seats) }; }),
    schedule: ({ destination, aircraftId = 'ec-nmr', price }) => withState(async (state) => { const now = Date.now(); const aircraft = state.aircraft.find(item => item.id === aircraftId); if (!aircraft) throw error('Avión no encontrado.', 404); if (aircraft.availableAt > now || aircraft.maintenanceUntil > now) throw error('Este avión todavía no está disponible.'); if (aircraft.condition < 65) throw error('El avión requiere mantenimiento antes de operar.'); const origin = aircraft.location; const quote = calculate(origin, destination, aircraft.seats); const fare = Number(price) || quote.fare; if (fare < 30 || fare > 999) throw error('La tarifa debe estar entre €30 y €999.'); const passengers = Math.min(aircraft.seats, Math.round(quote.expectedPassengers * Math.max(.72, Math.min(1.18, quote.fare / fare)))); const revenue = passengers * fare - quote.operatingCost; if (state.airline.cash < quote.operatingCost) throw error('No hay liquidez suficiente para cubrir los costes operativos.'); const code = `${state.airline.code}${String(state.flights.length + 204).padStart(3, '0')}`; const flight = { id: `flight-${Date.now()}`, code, aircraftId, aircraft: aircraft.model, origin, destination, departureAt: now + 5_000, arrivalAt: now + 5_000 + FLIGHT_DURATION_MS, durationHours: Math.round((quote.distance / 790) * 10) / 10, passengers, fare, operatingCost: quote.operatingCost, revenue, settled: false }; state.airline.cash -= quote.operatingCost; aircraft.availableAt = flight.arrivalAt + TURNAROUND_MS; state.ledger.unshift({ id: `ops-${flight.id}`, at: new Date(now).toISOString(), type: 'operating-cost', amount: -quote.operatingCost, note: `${code} · Costes operativos` }); state.flights.push(flight); return { value: { flight: publicFlight(flight, now), quote }, save: true }; }),
    maintain: ({ aircraftId = 'ec-nmr' }) => withState(async (state) => { const aircraft = state.aircraft.find(item => item.id === aircraftId); const now = Date.now(); if (!aircraft) throw error('Avión no encontrado.', 404); if (aircraft.availableAt > now) throw error('El avión está asignado a una operación.'); const cost = Math.round((100 - aircraft.condition) * 1_250 + 12_000); if (state.airline.cash < cost) throw error('No hay liquidez suficiente para mantenimiento.'); state.airline.cash -= cost; aircraft.maintenanceUntil = now + 15_000; aircraft.condition = 100; state.ledger.unshift({ id: `maintenance-${now}`, at: new Date(now).toISOString(), type: 'maintenance', amount: -cost, note: `${aircraft.registration} · Mantenimiento preventivo` }); return { value: { cost, availableAt: aircraft.maintenanceUntil }, save: true }; }),
    reset: () => transact(async () => { const state = template(); await save(state); return state; })
  };
}
module.exports = { createStore, calculate, flightStatus, distanceBetween };
